name: miboks
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^5.5.0
  curved_navigation_bar: ^1.0.1
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_spinkit: ^5.2.1
  intl: ^0.18.0
  path_provider: ^2.0.14
  pdf: ^3.10.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/cash.jpeg
    - assets/images/cash.png
    - assets/images/google.png
    - assets/images/login.jpeg
    - assets/images/miboks.png
    - assets/images/onboarding-1.png
    - assets/images/onboarding-2.png
    - assets/images/onboarding-3.png
    - assets/images/signup.jpeg
    - assets/images/birthday.png
    - assets/images/orange-money-logo.png

# Using custom splash screen implementation from splash_screen.dart
