name: miboks
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_dotenv: ^5.0.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.5.0
  intl: ^0.18.0
  pdf: ^3.10.0
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/cash.jpeg
    - assets/images/cash.png
    - assets/images/google.png
    - assets/images/login.jpeg
    - assets/images/miboks.png
    - assets/images/onboarding-1.png
    - assets/images/onboarding-2.png
    - assets/images/onboarding-3.png
    - assets/images/signup.jpeg

flutter_native_splash:
  color: "#ffffff" # Background color of the splash screen
  image: "assets/images/miboks.png" # Path to the splash screen image
  android: true # Enable splash screen for Android
  ios: true # Enable splash screen for iOS
  web: true # Enable splash screen for web
